minimum_pre_commit_version: "2"
default_language_version:
  python: python3
  node: 18.0.0

default_stages: [pre-commit]
fail_fast: false

exclude: |
  ^(\.vscode|\.github)|
  ^setup/|/static/description/index\.html$|
  ^(LICENSE.*|COPYING.*)$|
  ^\.pre-commit-config\.yaml$|
  ^\.prettierrc\.cjs$|
  ^\.ruff\.toml$

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2
    hooks:
      - id: ruff
        name: ruff-required
        args:
          - --config=.ruff.toml
          - --ignore=ERA,D,FBT002,UP031,SIM108,RUF100
          - --fix
          - --exit-non-zero-on-fix
      - id: ruff
        name: ruff-optional
        args:
          - --config=.ruff.toml
          - --select=ERA,D,FBT002,UP031,SIM108
          - --ignore=D1,D203,D205,D212,RUF100
          - --no-fix
          - --exit-zero
      - id: ruff
        name: ruff-cleanups
        args:
          - --config=.ruff.toml
          - --fix
          - --silent
          - --exit-zero
      - id: ruff-format
        name: ruff-format
        args:
          - --config=.ruff.toml

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: name-tests-test
        args: [--pytest-test-first]
        exclude: ^tests/(resources|fixtures)/
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args: [--autofix]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        name: codespell

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
      - id: python-safety-dependencies-check
        name: safety-check
        args: [--full-report]
